name: "Install Control Agent"
description: "Install control-plane agent VM and set up port forwarding"

inputs:
  ssh-host:
    description: "SSH host"
    required: true
  ssh-port:
    description: "SSH port"
    required: false
    default: "22"
  ssh-user:
    description: "SSH user"
    required: false
    default: "ubuntu"
  ssh-key:
    description: "SSH private key"
    required: true
  vm-name:
    description: "Control agent VM name"
    required: false
    default: "ee-control"
  vm-port:
    description: "Control agent VM port"
    required: false
    default: "8000"
  host-port:
    description: "Host port forwarded to control agent"
    required: false
    default: "443"
  public-ip:
    description: "Public IP mapped to control agent"
    required: false
    default: "57.130.10.246"
  dns-name:
    description: "DNS name for control agent (Cloudflare)"
    required: false
    default: "control.easyenclave.com"
  cloudflare-api-token:
    description: "Cloudflare API token (optional to update DNS)"
    required: false
    default: ""
  cloudflare-zone:
    description: "Cloudflare zone name"
    required: false
    default: "easyenclave.com"
  cloudflare-zone-id:
    description: "Cloudflare zone id (optional)"
    required: false
    default: ""
  cloudflare-proxied:
    description: "Whether to proxy the DNS record (true/false)"
    required: false
    default: "false"
  vm-image-tag:
    description: "Tag for pristine image build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Prepare SSH key
      id: ssh
      shell: bash
      run: |
        set -euo pipefail
        KEY_FILE=$(mktemp)
        chmod 600 "$KEY_FILE"
        printf '%s\n' "${{ inputs.ssh-key }}" > "$KEY_FILE"
        echo "file=$KEY_FILE" >> "$GITHUB_OUTPUT"

    - name: Install control agent
      shell: bash
      env:
        SSH_KEY_FILE: ${{ steps.ssh.outputs.file }}
        SSH_HOST: ${{ inputs.ssh-host }}
        SSH_PORT: ${{ inputs.ssh-port }}
        SSH_USER: ${{ inputs.ssh-user }}
        VM_NAME: ${{ inputs.vm-name }}
        VM_PORT: ${{ inputs.vm-port }}
        HOST_PORT: ${{ inputs.host-port }}
        PUBLIC_IP: ${{ inputs.public-ip }}
        VM_IMAGE_TAG: ${{ inputs.vm-image-tag }}
        CF_TOKEN: ${{ inputs.cloudflare-api-token }}
        CF_ZONE: ${{ inputs.cloudflare-zone }}
        CF_ZONE_ID: ${{ inputs.cloudflare-zone-id }}
        CF_PROXIED: ${{ inputs.cloudflare-proxied }}
        DNS_NAME: ${{ inputs.dns-name }}
      run: |
        set -euo pipefail
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -p "$SSH_PORT" -i "$SSH_KEY_FILE" "$SSH_USER@$SSH_HOST" <<EOF
        set -euo pipefail
        sudo rm -rf /opt/easy-enclave
        sudo git clone https://github.com/${{ github.repository }}.git /opt/easy-enclave
        cd /opt/easy-enclave
        sudo git fetch --tags origin
        sudo git checkout '${GITHUB_SHA}'
        sudo chmod +x installer/install.sh
        ARGS=(--non-interactive --vm-name '${VM_NAME}' --vm-port '${VM_PORT}')
        if [ -n '${HOST_PORT}' ]; then
          ARGS+=(--host-port '${HOST_PORT}')
        fi
        if [ -n '${PUBLIC_IP}' ]; then
          ARGS+=(--public-ip '${PUBLIC_IP}')
        fi
        if [ -n '${VM_IMAGE_TAG}' ]; then
          ARGS+=(--vm-image-tag '${VM_IMAGE_TAG}')
        fi
        sudo ./installer/install.sh "\${ARGS[@]}"
        if [ -n '${CF_TOKEN}' ] && [ -n '${DNS_NAME}' ]; then
          PROXY_FLAG="--dns-only"
          if [ '${CF_PROXIED}' = 'true' ]; then
            PROXY_FLAG="--proxied"
          fi
          python3 action/cloudflare_dns.py \
            --api-token '${CF_TOKEN}' \
            --zone '${CF_ZONE}' \
            --zone-id '${CF_ZONE_ID}' \
            --hosts '${DNS_NAME}' \
            --ip '${PUBLIC_IP}' \
            \${PROXY_FLAG}
        fi
        EOF
