name: "Reset Agents"
description: "Uninstall old agent VMs, reinstall control + contacts, and set up forwarding"

inputs:
  ssh-host:
    description: "SSH host for the hypervisor"
    required: true
  ssh-port:
    description: "SSH port"
    required: false
    default: "22"
  ssh-user:
    description: "SSH user"
    required: false
    default: "ubuntu"
  ssh-key:
    description: "SSH private key"
    required: true
  control-vm-name:
    description: "Control agent VM name"
    required: false
    default: "ee-control"
  control-vm-port:
    description: "Control agent VM port inside VM"
    required: false
    default: "8000"
  control-host-port:
    description: "Host port to forward to control agent"
    required: false
    default: "443"
  control-public-ip:
    description: "Public IP mapped to control agent"
    required: false
    default: "57.130.10.246"
  contact-vm-name:
    description: "Contacts agent VM name"
    required: false
    default: "ee-contacts"
  contact-vm-port:
    description: "Contacts agent VM port inside VM"
    required: false
    default: "8001"
  contact-host-port:
    description: "Host port to forward to contacts agent"
    required: false
    default: "443"
  contact-public-ip:
    description: "Public IP mapped to contacts agent"
    required: false
    default: "57.130.34.193"
  vm-image-tag:
    description: "Tag for pristine agent images"
    required: false
    default: ""
  cleanup-vms:
    description: "Space-separated VM names to destroy/undefine"
    required: false
    default: "ee-control ee-contacts ee-workload"

runs:
  using: "composite"
  steps:
    - name: Prepare SSH key
      id: ssh
      shell: bash
      run: |
        set -euo pipefail
        KEY_FILE=$(mktemp)
        chmod 600 "$KEY_FILE"
        printf '%s\n' "${{ inputs.ssh-key }}" > "$KEY_FILE"
        echo "file=$KEY_FILE" >> "$GITHUB_OUTPUT"

    - name: Reset agents on host
      shell: bash
      env:
        SSH_KEY_FILE: ${{ steps.ssh.outputs.file }}
        SSH_HOST: ${{ inputs.ssh-host }}
        SSH_PORT: ${{ inputs.ssh-port }}
        SSH_USER: ${{ inputs.ssh-user }}
        CONTROL_VM_NAME: ${{ inputs.control-vm-name }}
        CONTROL_VM_PORT: ${{ inputs.control-vm-port }}
        CONTROL_HOST_PORT: ${{ inputs.control-host-port }}
        CONTROL_PUBLIC_IP: ${{ inputs.control-public-ip }}
        CONTACT_VM_NAME: ${{ inputs.contact-vm-name }}
        CONTACT_VM_PORT: ${{ inputs.contact-vm-port }}
        CONTACT_HOST_PORT: ${{ inputs.contact-host-port }}
        CONTACT_PUBLIC_IP: ${{ inputs.contact-public-ip }}
        VM_IMAGE_TAG: ${{ inputs.vm-image-tag }}
        CLEANUP_VMS: ${{ inputs.cleanup-vms }}
      run: |
        set -euo pipefail
        ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" -i "$SSH_KEY_FILE" \
          "$SSH_USER@$SSH_HOST" <<EOF
set -euo pipefail
sudo rm -rf /opt/easy-enclave
sudo git clone https://github.com/${{ github.repository }}.git /opt/easy-enclave
cd /opt/easy-enclave
sudo git fetch --tags origin
sudo git checkout "${GITHUB_SHA}"
sudo chmod +x installer/reset_agents.sh
sudo ./installer/reset_agents.sh \
  --control-vm-name "${CONTROL_VM_NAME}" \
  --control-vm-port "${CONTROL_VM_PORT}" \
  --control-host-port "${CONTROL_HOST_PORT}" \
  --control-public-ip "${CONTROL_PUBLIC_IP}" \
  --contact-vm-name "${CONTACT_VM_NAME}" \
  --contact-vm-port "${CONTACT_VM_PORT}" \
  --contact-host-port "${CONTACT_HOST_PORT}" \
  --contact-public-ip "${CONTACT_PUBLIC_IP}" \
  --cleanup-vms "${CLEANUP_VMS}" \
  --vm-image-tag "${VM_IMAGE_TAG}"
EOF
