#cloud-config
write_files:
  - path: /opt/ee-agent/agent.py
    permissions: '0755'
    content: |
{agent_py}

  - path: /etc/systemd/system/ee-agent.service
    content: |
{agent_service}
{vm_image_id}

runcmd:
  - |
    bash -euxo pipefail -c '
      mkdir -p /etc/easy-enclave
      apt-get update
      apt-get install -y python3-venv
      python3 -m venv /opt/ee-agent/venv
      /opt/ee-agent/venv/bin/pip install --no-cache-dir aiohttp
      if ! apt-get install -y docker.io docker-compose-plugin; then
        if ! apt-get install -y docker.io docker-compose-v2; then
          apt-get install -y docker.io docker-compose
        fi
      fi
      systemctl enable --now docker
      systemctl daemon-reload
      systemctl enable ee-agent
      touch /etc/easy-enclave/agent-baked
      poweroff
    '
