#cloud-config
write_files:
  - path: /opt/ee-agent/agent.py
    permissions: '0755'
    content: |
{agent_py}

  - path: /opt/ee-agent/verify.py
    permissions: '0644'
    content: |
{agent_verify_py}

  - path: /opt/ee-agent/ratls.py
    permissions: '0644'
    content: |
{agent_ratls_py}

  - path: /etc/systemd/system/ee-agent.service
    content: |
{agent_service}
{vm_image_id}

runcmd:
  - |
    bash -euxo pipefail -c '
      export DEBIAN_FRONTEND=noninteractive
      proxy_host=$(ip route show default | cut -d " " -f3 | head -n1)
      if [ -n "$proxy_host" ] && timeout 1 bash -c "</dev/tcp/$proxy_host/3128" 2>/dev/null; then
        export http_proxy="http://$proxy_host:3128"
        export https_proxy="http://$proxy_host:3128"
        echo "Acquire::http::Proxy \"http://$proxy_host:3128\";" > /etc/apt/apt.conf.d/99proxy
        echo "Acquire::https::Proxy \"http://$proxy_host:3128\";" >> /etc/apt/apt.conf.d/99proxy
        mkdir -p /etc/systemd/system/docker.service.d
        printf "%s\n" \
          "[Service]" \
          "Environment=\"HTTP_PROXY=http://$proxy_host:3128\" \"HTTPS_PROXY=http://$proxy_host:3128\" \"NO_PROXY=localhost,127.0.0.1,::1\"" \
          > /etc/systemd/system/docker.service.d/http-proxy.conf
      fi
      retry() {{
        local attempts=5
        local delay=5
        local n=1
        while true; do
          if "$@"; then
            return 0
          fi
          if [ "$n" -ge "$attempts" ]; then
            return 1
          fi
          n=$((n + 1))
          sleep "$delay"
        done
      }}
      APT_OPTS="-o Acquire::Retries=3 -o Acquire::http::Timeout=20 -o Acquire::https::Timeout=20"
      mkdir -p /etc/easy-enclave
      retry apt-get update $APT_OPTS
      retry apt-get install -y $APT_OPTS python3-venv
      python3 -m venv /opt/ee-agent/venv
      retry /opt/ee-agent/venv/bin/pip install --no-cache-dir aiohttp cryptography requests
      if ! retry apt-get install -y $APT_OPTS docker.io docker-compose-plugin; then
        if ! retry apt-get install -y $APT_OPTS docker.io docker-compose-v2; then
          retry apt-get install -y $APT_OPTS docker.io docker-compose
        fi
      fi
      systemctl daemon-reload
      systemctl enable --now docker
      systemctl enable --now ee-agent
    '
