#cloud-config
write_files:
  - path: /opt/ee-agent/agent.py
    permissions: '0755'
    content: |
{agent_py}

  - path: /opt/ee-agent/verify.py
    permissions: '0644'
    content: |
{agent_verify_py}

  - path: /opt/ee-agent/ratls.py
    permissions: '0644'
    content: |
{agent_ratls_py}

  - path: /etc/systemd/system/ee-agent.service
    content: |
{agent_service}
{vm_image_id}

runcmd:
  - |
    bash -euxo pipefail -c '
      export DEBIAN_FRONTEND=noninteractive
      trap "sync; poweroff -f" EXIT
      proxy_host=$(ip route show default | cut -d " " -f3 | head -n1)
      if [ -n "$proxy_host" ] && timeout 1 bash -c "</dev/tcp/$proxy_host/3128" 2>/dev/null; then
        export http_proxy="http://$proxy_host:3128"
        export https_proxy="http://$proxy_host:3128"
        echo "Acquire::http::Proxy \"http://$proxy_host:3128\";" > /etc/apt/apt.conf.d/99proxy
        echo "Acquire::https::Proxy \"http://$proxy_host:3128\";" >> /etc/apt/apt.conf.d/99proxy
      fi
      retry() {{
        local attempts=5
        local delay=5
        local n=1
        while true; do
          if "$@"; then
            return 0
          fi
          if [ "$n" -ge "$attempts" ]; then
            return 1
          fi
          n=$((n + 1))
          sleep "$delay"
        done
      }}
      mkdir -p /etc/easy-enclave
      retry apt-get update
      retry apt-get install -y python3-venv
      python3 -m venv /opt/ee-agent/venv
      retry /opt/ee-agent/venv/bin/pip install --no-cache-dir aiohttp cryptography requests
      if ! retry apt-get install -y docker.io docker-compose-plugin; then
        if ! retry apt-get install -y docker.io docker-compose-v2; then
          retry apt-get install -y docker.io docker-compose
        fi
      fi
      systemctl enable --now docker
      systemctl daemon-reload
      systemctl enable ee-agent
      touch /etc/easy-enclave/agent-baked
    '
