#cloud-config
write_files:
  - path: /opt/ee-agent/agent.py
    permissions: '0755'
    content: |
{agent_py}

  - path: /opt/ee-agent/verify.py
    permissions: '0644'
    content: |
{agent_verify_py}

  - path: /opt/ee-agent/ratls.py
    permissions: '0644'
    content: |
{agent_ratls_py}

  - path: /opt/ee-agent/control_plane/__init__.py
    permissions: '0644'
    content: |
{control_plane_init_py}

  - path: /opt/ee-agent/control_plane/server.py
    permissions: '0644'
    content: |
{control_plane_server_py}

  - path: /opt/ee-agent/control_plane/config.py
    permissions: '0644'
    content: |
{control_plane_config_py}

  - path: /opt/ee-agent/control_plane/allowlist.py
    permissions: '0644'
    content: |
{control_plane_allowlist_py}

  - path: /opt/ee-agent/control_plane/ledger.py
    permissions: '0644'
    content: |
{control_plane_ledger_py}

  - path: /opt/ee-agent/control_plane/policy.py
    permissions: '0644'
    content: |
{control_plane_policy_py}

  - path: /opt/ee-agent/control_plane/registry.py
    permissions: '0644'
    content: |
{control_plane_registry_py}

  - path: /opt/ee-agent/control_plane/ratls.py
    permissions: '0644'
    content: |
{control_plane_ratls_py}

  - path: /opt/ee-agent/control_plane/static/admin.html
    permissions: '0644'
    content: |
{control_plane_admin_html}

  - path: /opt/ee-agent/easyenclave/__init__.py
    permissions: '0644'
    content: |
{sdk_init_py}

  - path: /opt/ee-agent/easyenclave/connect.py
    permissions: '0644'
    content: |
{sdk_connect_py}

  - path: /opt/ee-agent/easyenclave/exceptions.py
    permissions: '0644'
    content: |
{sdk_exceptions_py}

  - path: /opt/ee-agent/easyenclave/github.py
    permissions: '0644'
    content: |
{sdk_github_py}

  - path: /opt/ee-agent/easyenclave/ratls.py
    permissions: '0644'
    content: |
{sdk_ratls_py}

  - path: /opt/ee-agent/easyenclave/verify.py
    permissions: '0644'
    content: |
{sdk_verify_py}

  - path: /etc/easy-enclave/agent.env
    permissions: '0640'
    content: |
{agent_env}

  - path: /etc/easy-enclave/control-allowlist.json
    permissions: '0644'
    content: |
{control_allowlist_json}

  - path: /opt/ee-agent/nginx.conf
    permissions: '0644'
    content: |
{nginx_conf}

  - path: /etc/systemd/system/ee-agent.service
    content: |
{agent_service}
{vm_image_id}

runcmd:
  - |
    bash -euxo pipefail -c '
      export DEBIAN_FRONTEND=noninteractive
      if ! ip route show default >/dev/null 2>&1; then
        lease_gw=""
        for lease in /run/systemd/netif/leases/*; do
          if [ -f "$lease" ]; then
            lease_gw=$(awk -F= "/^ROUTER=/ {print $2; exit}" "$lease")
            if [ -n "$lease_gw" ]; then
              break
            fi
          fi
        done
        if [ -z "$lease_gw" ]; then
          lease_gw="192.168.122.1"
        fi
        ip route add default via "$lease_gw" || true
      fi
      proxy_host=$(ip route show default | cut -d " " -f3 | head -n1)
      if [ -n "$proxy_host" ] && timeout 1 bash -c "</dev/tcp/$proxy_host/3128" 2>/dev/null; then
        export http_proxy="http://$proxy_host:3128"
        export https_proxy="http://$proxy_host:3128"
        echo "Acquire::http::Proxy \"http://$proxy_host:3128\";" > /etc/apt/apt.conf.d/99proxy
        echo "Acquire::https::Proxy \"http://$proxy_host:3128\";" >> /etc/apt/apt.conf.d/99proxy
        mkdir -p /etc/systemd/system/docker.service.d
        printf "%s\n" \
          "[Service]" \
          "Environment=\"HTTP_PROXY=http://$proxy_host:3128\" \"HTTPS_PROXY=http://$proxy_host:3128\" \"NO_PROXY=localhost,127.0.0.1,::1\"" \
          > /etc/systemd/system/docker.service.d/http-proxy.conf
      fi
      retry() {{
        local attempts=5
        local delay=5
        local n=1
        while true; do
          if "$@"; then
            return 0
          fi
          if [ "$n" -ge "$attempts" ]; then
            return 1
          fi
          n=$((n + 1))
          sleep "$delay"
        done
      }}
      APT_OPTS="-o Acquire::Retries=3 -o Acquire::http::Timeout=20 -o Acquire::https::Timeout=20"
      mkdir -p /etc/easy-enclave
      retry apt-get update $APT_OPTS
      retry apt-get install -y $APT_OPTS python3-venv nginx libnginx-mod-stream openssl
      install -m 0644 /opt/ee-agent/nginx.conf /etc/nginx/nginx.conf
      python3 -m venv /opt/ee-agent/venv
      retry /opt/ee-agent/venv/bin/pip install --no-cache-dir aiohttp cryptography requests
      if ! retry apt-get install -y $APT_OPTS docker.io docker-compose-plugin; then
        if ! retry apt-get install -y $APT_OPTS docker.io docker-compose-v2; then
          retry apt-get install -y $APT_OPTS docker.io docker-compose
        fi
      fi
      mkdir -p /etc/nginx/ssl
      if [ ! -f /etc/nginx/ssl/admin.key ]; then
        openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
          -subj "/CN=admin.easyenclave.local" \
          -keyout /etc/nginx/ssl/admin.key \
          -out /etc/nginx/ssl/admin.crt
      fi
      systemctl daemon-reload
      systemctl enable --now docker
      systemctl enable --now nginx
      systemctl enable --now ee-agent
    '
